// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerixSoftMvc.Data;

#nullable disable

namespace VerixSoftMvc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VerixSoftMvc.Models.Benefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Benefits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "Agile Development Methodology"
                        },
                        new
                        {
                            Id = 2,
                            Text = "24/7 Technical Support"
                        },
                        new
                        {
                            Id = 3,
                            Text = "Transparent Communication"
                        },
                        new
                        {
                            Id = 4,
                            Text = "On-time Delivery Guarantee"
                        },
                        new
                        {
                            Id = 5,
                            Text = "Quality Assurance"
                        },
                        new
                        {
                            Id = 6,
                            Text = "Scalable Solutions"
                        });
                });

            modelBuilder.Entity("VerixSoftMvc.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Custom web applications built with cutting-edge technologies for optimal performance and scalability.",
                            IconName = "Code2",
                            Title = "Web Development"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Native and cross-platform mobile solutions that deliver exceptional user experiences.",
                            IconName = "Smartphone",
                            Title = "Mobile Apps"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Scalable cloud infrastructure and migration services for modern businesses.",
                            IconName = "Cloud",
                            Title = "Cloud Solutions"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Intelligent automation and machine learning solutions to drive innovation.",
                            IconName = "Brain",
                            Title = "AI/ML Integration"
                        });
                });

            modelBuilder.Entity("VerixSoftMvc.Models.Stat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Projects Delivered",
                            Number = "100+"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Happy Clients",
                            Number = "80+"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Team Members",
                            Number = "10+"
                        },
                        new
                        {
                            Id = 4,
                            Label = "Years Experience",
                            Number = "2+"
                        });
                });

            modelBuilder.Entity("VerixSoftMvc.Models.TechStack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TechStacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Frontend",
                            LogoUrl = "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
                            Name = "React"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Frontend",
                            LogoUrl = "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg",
                            Name = "Next.js"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Frontend",
                            LogoUrl = "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Backend",
                            LogoUrl = "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg",
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Backend",
                            LogoUrl = "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/dotnetcore/dotnetcore-original.svg",
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Database",
                            LogoUrl = "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/microsoftsqlserver/microsoftsqlserver-plain.svg",
                            Name = "SQL Server"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
